# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CameraApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CameraApp
  pod 'R.swift' , '~> 7.2'

  target 'CameraAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CameraAppUITests' do
    # Pods for testing
  end

end
